# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_petunjuk.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 489)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/logo_unikom_kuning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Judul = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Judul.sizePolicy().hasHeightForWidth())
        self.Judul.setSizePolicy(sizePolicy)
        self.Judul.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Judul.setFont(font)
        self.Judul.setStyleSheet("background-color:white")
        self.Judul.setAlignment(QtCore.Qt.AlignCenter)
        self.Judul.setObjectName("Judul")
        self.verticalLayout.addWidget(self.Judul)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pbPrevious = QtWidgets.QPushButton(self.frame)
        self.pbPrevious.setMinimumSize(QtCore.QSize(50, 50))
        self.pbPrevious.setMaximumSize(QtCore.QSize(30, 30))
        self.pbPrevious.setObjectName("pbPrevious")
        self.gridLayout.addWidget(self.pbPrevious, 0, 1, 1, 1)
        self.pbNext = QtWidgets.QPushButton(self.frame)
        self.pbNext.setMinimumSize(QtCore.QSize(50, 50))
        self.pbNext.setMaximumSize(QtCore.QSize(30, 30))
        self.pbNext.setObjectName("pbNext")
        self.gridLayout.addWidget(self.pbNext, 0, 3, 1, 1)
        self.idxGambar = QtWidgets.QLabel(self.frame)
        self.idxGambar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.idxGambar.setAlignment(QtCore.Qt.AlignCenter)
        self.idxGambar.setObjectName("idxGambar")
        self.gridLayout.addWidget(self.idxGambar, 1, 2, 1, 1)
        self.Gambar = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gambar.sizePolicy().hasHeightForWidth())
        self.Gambar.setSizePolicy(sizePolicy)
        self.Gambar.setMinimumSize(QtCore.QSize(300, 300))
        self.Gambar.setScaledContents(True)
        self.Gambar.setAlignment(QtCore.Qt.AlignCenter)
        self.Gambar.setObjectName("Gambar")
        self.gridLayout.addWidget(self.Gambar, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pbOk = QtWidgets.QPushButton(self.frame_2)
        self.pbOk.setMinimumSize(QtCore.QSize(100, 30))
        self.pbOk.setObjectName("pbOk")
        self.horizontalLayout_2.addWidget(self.pbOk)
        spacerItem3 = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Judul.setText(_translate("MainWindow", "Petunjuk Penggunaan"))
        self.pbPrevious.setText(_translate("MainWindow", "<"))
        self.pbNext.setText(_translate("MainWindow", ">"))
        self.idxGambar.setText(_translate("MainWindow", "Index Gambar"))
        self.Gambar.setText(_translate("MainWindow", "Gambar"))
        self.pbOk.setText(_translate("MainWindow", "OK"))
import gui.sourcesGambar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
