# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_pelatihan.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1069, 645)
        MainMenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainMenu.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 3)
        self.gridLayout_11.setVerticalSpacing(3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.judul = QtWidgets.QLabel(self.centralwidget)
        self.judul.setEnabled(True)
        self.judul.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.judul.setFont(font)
        self.judul.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.judul.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.judul.setLineWidth(0)
        self.judul.setTextFormat(QtCore.Qt.PlainText)
        self.judul.setScaledContents(False)
        self.judul.setAlignment(QtCore.Qt.AlignCenter)
        self.judul.setIndent(0)
        self.judul.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.judul.setObjectName("judul")
        self.gridLayout_11.addWidget(self.judul, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_8.setSpacing(3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.f_pengujian = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_pengujian.sizePolicy().hasHeightForWidth())
        self.f_pengujian.setSizePolicy(sizePolicy)
        self.f_pengujian.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.f_pengujian.setFlat(False)
        self.f_pengujian.setObjectName("f_pengujian")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.f_pengujian)
        self.gridLayout_10.setContentsMargins(0, 0, 3, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Tools_2 = QtWidgets.QFrame(self.f_pengujian)
        self.Tools_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Tools_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Tools_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Tools_2.setObjectName("Tools_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Tools_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Tombol_2 = QtWidgets.QGroupBox(self.Tools_2)
        self.Tombol_2.setTabletTracking(False)
        self.Tombol_2.setAcceptDrops(False)
        self.Tombol_2.setAutoFillBackground(False)
        self.Tombol_2.setStyleSheet("background-color: rgb(217, 217, 217),")
        self.Tombol_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Tombol_2.setFlat(True)
        self.Tombol_2.setCheckable(False)
        self.Tombol_2.setObjectName("Tombol_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Tombol_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pbBaca_2 = QtWidgets.QPushButton(self.Tombol_2)
        self.pbBaca_2.setDefault(False)
        self.pbBaca_2.setObjectName("pbBaca_2")
        self.verticalLayout_10.addWidget(self.pbBaca_2)
        self.pbPengujian = QtWidgets.QPushButton(self.Tombol_2)
        self.pbPengujian.setObjectName("pbPengujian")
        self.verticalLayout_10.addWidget(self.pbPengujian)
        self.verticalLayout_13.addWidget(self.Tombol_2)
        self.TotalData_2 = QtWidgets.QGroupBox(self.Tools_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TotalData_2.sizePolicy().hasHeightForWidth())
        self.TotalData_2.setSizePolicy(sizePolicy)
        self.TotalData_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TotalData_2.setStyleSheet("background-color: rgb(217, 217, 217),")
        self.TotalData_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalData_2.setFlat(True)
        self.TotalData_2.setObjectName("TotalData_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.TotalData_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.eTotalDUji = QtWidgets.QLineEdit(self.TotalData_2)
        self.eTotalDUji.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eTotalDUji.setInputMask("")
        self.eTotalDUji.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.eTotalDUji.setAlignment(QtCore.Qt.AlignCenter)
        self.eTotalDUji.setReadOnly(True)
        self.eTotalDUji.setObjectName("eTotalDUji")
        self.verticalLayout_12.addWidget(self.eTotalDUji)
        self.verticalLayout_13.addWidget(self.TotalData_2)
        self.Iterasi_2 = QtWidgets.QGroupBox(self.Tools_2)
        self.Iterasi_2.setTabletTracking(False)
        self.Iterasi_2.setAcceptDrops(False)
        self.Iterasi_2.setAutoFillBackground(False)
        self.Iterasi_2.setStyleSheet("background-color: rgb(217, 217, 217),")
        self.Iterasi_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Iterasi_2.setFlat(True)
        self.Iterasi_2.setCheckable(False)
        self.Iterasi_2.setObjectName("Iterasi_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Iterasi_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lWaktu_2 = QtWidgets.QLabel(self.Iterasi_2)
        self.lWaktu_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lWaktu_2.setObjectName("lWaktu_2")
        self.verticalLayout_11.addWidget(self.lWaktu_2)
        self.eWaktu_2 = QtWidgets.QLineEdit(self.Iterasi_2)
        self.eWaktu_2.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eWaktu_2.setAlignment(QtCore.Qt.AlignCenter)
        self.eWaktu_2.setReadOnly(True)
        self.eWaktu_2.setObjectName("eWaktu_2")
        self.verticalLayout_11.addWidget(self.eWaktu_2)
        self.lMSE_2 = QtWidgets.QLabel(self.Iterasi_2)
        self.lMSE_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lMSE_2.setObjectName("lMSE_2")
        self.verticalLayout_11.addWidget(self.lMSE_2)
        self.eMSE_2 = QtWidgets.QLineEdit(self.Iterasi_2)
        self.eMSE_2.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eMSE_2.setAlignment(QtCore.Qt.AlignCenter)
        self.eMSE_2.setReadOnly(True)
        self.eMSE_2.setObjectName("eMSE_2")
        self.verticalLayout_11.addWidget(self.eMSE_2)
        self.lAkurasi = QtWidgets.QLabel(self.Iterasi_2)
        self.lAkurasi.setAlignment(QtCore.Qt.AlignCenter)
        self.lAkurasi.setObjectName("lAkurasi")
        self.verticalLayout_11.addWidget(self.lAkurasi)
        self.eAkurasi = QtWidgets.QLineEdit(self.Iterasi_2)
        self.eAkurasi.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eAkurasi.setAlignment(QtCore.Qt.AlignCenter)
        self.eAkurasi.setReadOnly(True)
        self.eAkurasi.setObjectName("eAkurasi")
        self.verticalLayout_11.addWidget(self.eAkurasi)
        self.verticalLayout_13.addWidget(self.Iterasi_2)
        self.groupBox = QtWidgets.QGroupBox(self.Tools_2)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pbDetailG_2 = QtWidgets.QPushButton(self.groupBox)
        self.pbDetailG_2.setObjectName("pbDetailG_2")
        self.verticalLayout_6.addWidget(self.pbDetailG_2)
        self.verticalLayout_13.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.gExtra = QtWidgets.QGroupBox(self.Tools_2)
        self.gExtra.setTitle("")
        self.gExtra.setFlat(True)
        self.gExtra.setObjectName("gExtra")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gExtra)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pbKelola = QtWidgets.QPushButton(self.gExtra)
        self.pbKelola.setObjectName("pbKelola")
        self.verticalLayout_7.addWidget(self.pbKelola)
        self.pbCetak = QtWidgets.QPushButton(self.gExtra)
        self.pbCetak.setObjectName("pbCetak")
        self.verticalLayout_7.addWidget(self.pbCetak)
        self.verticalLayout_13.addWidget(self.gExtra)
        self.gridLayout_10.addWidget(self.Tools_2, 0, 0, 1, 1)
        self.Tabel_2 = QtWidgets.QFrame(self.f_pengujian)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabel_2.sizePolicy().hasHeightForWidth())
        self.Tabel_2.setSizePolicy(sizePolicy)
        self.Tabel_2.setMinimumSize(QtCore.QSize(369, 0))
        self.Tabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Tabel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Tabel_2.setObjectName("Tabel_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Tabel_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DataUji = QtWidgets.QGroupBox(self.Tabel_2)
        self.DataUji.setObjectName("DataUji")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.DataUji)
        self.gridLayout_7.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tbDataUji = QtWidgets.QTableWidget(self.DataUji)
        self.tbDataUji.setMinimumSize(QtCore.QSize(0, 170))
        self.tbDataUji.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tbDataUji.setAutoFillBackground(True)
        self.tbDataUji.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbDataUji.setAlternatingRowColors(True)
        self.tbDataUji.setObjectName("tbDataUji")
        self.tbDataUji.setColumnCount(20)
        self.tbDataUji.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataUji.setHorizontalHeaderItem(19, item)
        self.tbDataUji.horizontalHeader().setDefaultSectionSize(60)
        self.tbDataUji.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout_7.addWidget(self.tbDataUji, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.DataUji, 0, 0, 1, 1)
        self.HasilUji = QtWidgets.QGroupBox(self.Tabel_2)
        self.HasilUji.setMinimumSize(QtCore.QSize(0, 150))
        self.HasilUji.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.HasilUji.setObjectName("HasilUji")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.HasilUji)
        self.gridLayout_6.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tbHasilUji = QtWidgets.QTableWidget(self.HasilUji)
        self.tbHasilUji.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbHasilUji.setAlternatingRowColors(True)
        self.tbHasilUji.setObjectName("tbHasilUji")
        self.tbHasilUji.setColumnCount(5)
        self.tbHasilUji.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbHasilUji.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbHasilUji.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbHasilUji.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbHasilUji.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbHasilUji.setHorizontalHeaderItem(4, item)
        self.tbHasilUji.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout_6.addWidget(self.tbHasilUji, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.HasilUji, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.Tabel_2, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.f_pengujian, 2, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbLogout = QtWidgets.QPushButton(self.frame_2)
        self.pbLogout.setMinimumSize(QtCore.QSize(150, 0))
        self.pbLogout.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pbLogout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pbLogout.setObjectName("pbLogout")
        self.horizontalLayout.addWidget(self.pbLogout)
        self.pbTambah = QtWidgets.QPushButton(self.frame_2)
        self.pbTambah.setMinimumSize(QtCore.QSize(150, 0))
        self.pbTambah.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pbTambah.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pbTambah.setObjectName("pbTambah")
        self.horizontalLayout.addWidget(self.pbTambah)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_8.addWidget(self.frame_2, 0, 1, 1, 1)
        self.f_pelatihan = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_pelatihan.sizePolicy().hasHeightForWidth())
        self.f_pelatihan.setSizePolicy(sizePolicy)
        self.f_pelatihan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.f_pelatihan.setAcceptDrops(False)
        self.f_pelatihan.setFlat(False)
        self.f_pelatihan.setCheckable(False)
        self.f_pelatihan.setObjectName("f_pelatihan")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.f_pelatihan)
        self.gridLayout_9.setContentsMargins(3, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Tools = QtWidgets.QFrame(self.f_pelatihan)
        self.Tools.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Tools.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Tools.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Tools.setObjectName("Tools")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Tools)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Tombol = QtWidgets.QGroupBox(self.Tools)
        self.Tombol.setTabletTracking(False)
        self.Tombol.setAcceptDrops(False)
        self.Tombol.setAutoFillBackground(False)
        self.Tombol.setStyleSheet("background-color: rgb(217, 217, 217),")
        self.Tombol.setAlignment(QtCore.Qt.AlignCenter)
        self.Tombol.setFlat(True)
        self.Tombol.setCheckable(False)
        self.Tombol.setObjectName("Tombol")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Tombol)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pbBaca = QtWidgets.QPushButton(self.Tombol)
        self.pbBaca.setAcceptDrops(False)
        self.pbBaca.setCheckable(False)
        self.pbBaca.setDefault(True)
        self.pbBaca.setFlat(False)
        self.pbBaca.setObjectName("pbBaca")
        self.verticalLayout_3.addWidget(self.pbBaca)
        self.pbBobot = QtWidgets.QPushButton(self.Tombol)
        self.pbBobot.setObjectName("pbBobot")
        self.verticalLayout_3.addWidget(self.pbBobot)
        self.pbPelatihan = QtWidgets.QPushButton(self.Tombol)
        self.pbPelatihan.setObjectName("pbPelatihan")
        self.verticalLayout_3.addWidget(self.pbPelatihan)
        self.verticalLayout_2.addWidget(self.Tombol)
        self.TotalData = QtWidgets.QGroupBox(self.Tools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TotalData.sizePolicy().hasHeightForWidth())
        self.TotalData.setSizePolicy(sizePolicy)
        self.TotalData.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TotalData.setTabletTracking(False)
        self.TotalData.setAcceptDrops(False)
        self.TotalData.setAutoFillBackground(False)
        self.TotalData.setStyleSheet("background-color: rgb(217, 217, 217),")
        self.TotalData.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalData.setFlat(True)
        self.TotalData.setCheckable(False)
        self.TotalData.setObjectName("TotalData")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.TotalData)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.eTotalDLatih = QtWidgets.QLineEdit(self.TotalData)
        self.eTotalDLatih.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eTotalDLatih.setInputMask("")
        self.eTotalDLatih.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.eTotalDLatih.setAlignment(QtCore.Qt.AlignCenter)
        self.eTotalDLatih.setReadOnly(True)
        self.eTotalDLatih.setObjectName("eTotalDLatih")
        self.verticalLayout_4.addWidget(self.eTotalDLatih)
        self.verticalLayout_2.addWidget(self.TotalData)
        self.Parameter = QtWidgets.QGroupBox(self.Tools)
        self.Parameter.setTabletTracking(False)
        self.Parameter.setAcceptDrops(False)
        self.Parameter.setAutoFillBackground(False)
        self.Parameter.setStyleSheet("background-color: rgb(217, 217, 217),")
        self.Parameter.setAlignment(QtCore.Qt.AlignCenter)
        self.Parameter.setFlat(True)
        self.Parameter.setCheckable(False)
        self.Parameter.setObjectName("Parameter")
        self.formLayout = QtWidgets.QFormLayout(self.Parameter)
        self.formLayout.setObjectName("formLayout")
        self.lNInp = QtWidgets.QLabel(self.Parameter)
        self.lNInp.setObjectName("lNInp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lNInp)
        self.lNHid = QtWidgets.QLabel(self.Parameter)
        self.lNHid.setObjectName("lNHid")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lNHid)
        self.lNOut = QtWidgets.QLabel(self.Parameter)
        self.lNOut.setObjectName("lNOut")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lNOut)
        self.lAlpha = QtWidgets.QLabel(self.Parameter)
        self.lAlpha.setObjectName("lAlpha")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lAlpha)
        self.lMinE = QtWidgets.QLabel(self.Parameter)
        self.lMinE.setObjectName("lMinE")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lMinE)
        self.lIte = QtWidgets.QLabel(self.Parameter)
        self.lIte.setObjectName("lIte")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lIte)
        self.eNInp = QtWidgets.QLineEdit(self.Parameter)
        self.eNInp.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eNInp.setAlignment(QtCore.Qt.AlignCenter)
        self.eNInp.setReadOnly(True)
        self.eNInp.setObjectName("eNInp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.eNInp)
        self.eNHid = QtWidgets.QLineEdit(self.Parameter)
        self.eNHid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.eNHid.setAlignment(QtCore.Qt.AlignCenter)
        self.eNHid.setReadOnly(False)
        self.eNHid.setObjectName("eNHid")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.eNHid)
        self.eNOut = QtWidgets.QLineEdit(self.Parameter)
        self.eNOut.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eNOut.setAlignment(QtCore.Qt.AlignCenter)
        self.eNOut.setReadOnly(True)
        self.eNOut.setObjectName("eNOut")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.eNOut)
        self.eAlpha = QtWidgets.QLineEdit(self.Parameter)
        self.eAlpha.setStyleSheet("background-color: rgb(255, 255, 255),")
        self.eAlpha.setObjectName("eAlpha")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eAlpha)
        self.eMinE = QtWidgets.QLineEdit(self.Parameter)
        self.eMinE.setStyleSheet("background-color: rgb(255, 255, 255),")
        self.eMinE.setObjectName("eMinE")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.eMinE)
        self.eIte = QtWidgets.QLineEdit(self.Parameter)
        self.eIte.setStyleSheet("background-color: rgb(255, 255, 255),")
        self.eIte.setObjectName("eIte")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.eIte)
        self.verticalLayout_2.addWidget(self.Parameter)
        self.Iterasi = QtWidgets.QGroupBox(self.Tools)
        self.Iterasi.setTabletTracking(False)
        self.Iterasi.setAcceptDrops(False)
        self.Iterasi.setAutoFillBackground(False)
        self.Iterasi.setStyleSheet("background-color: rgb(217, 217, 217),")
        self.Iterasi.setAlignment(QtCore.Qt.AlignCenter)
        self.Iterasi.setFlat(True)
        self.Iterasi.setCheckable(False)
        self.Iterasi.setObjectName("Iterasi")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Iterasi)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lWaktu = QtWidgets.QLabel(self.Iterasi)
        self.lWaktu.setAlignment(QtCore.Qt.AlignCenter)
        self.lWaktu.setObjectName("lWaktu")
        self.verticalLayout_5.addWidget(self.lWaktu)
        self.eWaktu = QtWidgets.QLineEdit(self.Iterasi)
        self.eWaktu.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eWaktu.setAlignment(QtCore.Qt.AlignCenter)
        self.eWaktu.setReadOnly(True)
        self.eWaktu.setObjectName("eWaktu")
        self.verticalLayout_5.addWidget(self.eWaktu)
        self.lMSE = QtWidgets.QLabel(self.Iterasi)
        self.lMSE.setAlignment(QtCore.Qt.AlignCenter)
        self.lMSE.setObjectName("lMSE")
        self.verticalLayout_5.addWidget(self.lMSE)
        self.eMSE = QtWidgets.QLineEdit(self.Iterasi)
        self.eMSE.setStyleSheet("background-color: rgb(246, 255, 98);")
        self.eMSE.setAlignment(QtCore.Qt.AlignCenter)
        self.eMSE.setReadOnly(True)
        self.eMSE.setObjectName("eMSE")
        self.verticalLayout_5.addWidget(self.eMSE)
        self.verticalLayout_2.addWidget(self.Iterasi)
        self.TombolGrafik = QtWidgets.QGroupBox(self.Tools)
        self.TombolGrafik.setAlignment(QtCore.Qt.AlignCenter)
        self.TombolGrafik.setFlat(True)
        self.TombolGrafik.setObjectName("TombolGrafik")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TombolGrafik)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbDetailG = QtWidgets.QPushButton(self.TombolGrafik)
        self.pbDetailG.setObjectName("pbDetailG")
        self.verticalLayout.addWidget(self.pbDetailG)
        self.verticalLayout_2.addWidget(self.TombolGrafik)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_9.addWidget(self.Tools, 0, 0, 1, 1)
        self.Tabel = QtWidgets.QFrame(self.f_pelatihan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabel.sizePolicy().hasHeightForWidth())
        self.Tabel.setSizePolicy(sizePolicy)
        self.Tabel.setMinimumSize(QtCore.QSize(369, 0))
        self.Tabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Tabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Tabel.setObjectName("Tabel")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.Tabel)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.BobotHasil = QtWidgets.QGroupBox(self.Tabel)
        self.BobotHasil.setMinimumSize(QtCore.QSize(0, 150))
        self.BobotHasil.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BobotHasil.setObjectName("BobotHasil")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.BobotHasil)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tbBobotW = QtWidgets.QTableWidget(self.BobotHasil)
        self.tbBobotW.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tbBobotW.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbBobotW.setProperty("showDropIndicator", True)
        self.tbBobotW.setDragDropOverwriteMode(False)
        self.tbBobotW.setAlternatingRowColors(True)
        self.tbBobotW.setObjectName("tbBobotW")
        self.tbBobotW.setColumnCount(0)
        self.tbBobotW.setRowCount(0)
        self.tbBobotW.horizontalHeader().setDefaultSectionSize(60)
        self.tbBobotW.horizontalHeader().setMinimumSectionSize(25)
        self.gridLayout_2.addWidget(self.tbBobotW, 1, 1, 1, 1)
        self.tbBobotV = QtWidgets.QTableWidget(self.BobotHasil)
        self.tbBobotV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tbBobotV.setAutoFillBackground(True)
        self.tbBobotV.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbBobotV.setDragDropOverwriteMode(False)
        self.tbBobotV.setAlternatingRowColors(True)
        self.tbBobotV.setObjectName("tbBobotV")
        self.tbBobotV.setColumnCount(0)
        self.tbBobotV.setRowCount(0)
        self.tbBobotV.horizontalHeader().setDefaultSectionSize(60)
        self.tbBobotV.horizontalHeader().setMinimumSectionSize(25)
        self.gridLayout_2.addWidget(self.tbBobotV, 1, 0, 1, 1)
        self.lBobotV = QtWidgets.QLabel(self.BobotHasil)
        self.lBobotV.setObjectName("lBobotV")
        self.gridLayout_2.addWidget(self.lBobotV, 0, 0, 1, 1)
        self.lBobotW = QtWidgets.QLabel(self.BobotHasil)
        self.lBobotW.setObjectName("lBobotW")
        self.gridLayout_2.addWidget(self.lBobotW, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.BobotHasil, 1, 0, 1, 1)
        self.DataLatih = QtWidgets.QGroupBox(self.Tabel)
        self.DataLatih.setObjectName("DataLatih")
        self.gridLayout = QtWidgets.QGridLayout(self.DataLatih)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tbDataLat = QtWidgets.QTableWidget(self.DataLatih)
        self.tbDataLat.setMinimumSize(QtCore.QSize(0, 170))
        self.tbDataLat.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tbDataLat.setAutoFillBackground(True)
        self.tbDataLat.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbDataLat.setAlternatingRowColors(True)
        self.tbDataLat.setObjectName("tbDataLat")
        self.tbDataLat.setColumnCount(20)
        self.tbDataLat.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tbDataLat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataLat.setHorizontalHeaderItem(19, item)
        self.tbDataLat.horizontalHeader().setDefaultSectionSize(60)
        self.gridLayout.addWidget(self.tbDataLat, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.DataLatih, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.Tabel, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.f_pelatihan, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lHelo = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lHelo.sizePolicy().hasHeightForWidth())
        self.lHelo.setSizePolicy(sizePolicy)
        self.lHelo.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lHelo.setFont(font)
        self.lHelo.setIndent(5)
        self.lHelo.setObjectName("lHelo")
        self.horizontalLayout_2.addWidget(self.lHelo)
        self.lAdmin = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lAdmin.setFont(font)
        self.lAdmin.setIndent(-1)
        self.lAdmin.setObjectName("lAdmin")
        self.horizontalLayout_2.addWidget(self.lAdmin)
        self.gridLayout_8.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame, 2, 0, 1, 1)
        MainMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)
        MainMenu.setTabOrder(self.tbDataUji, self.eNHid)
        MainMenu.setTabOrder(self.eNHid, self.tbBobotV)
        MainMenu.setTabOrder(self.tbBobotV, self.tbBobotW)
        MainMenu.setTabOrder(self.tbBobotW, self.tbHasilUji)
        MainMenu.setTabOrder(self.tbHasilUji, self.tbDataLat)
        MainMenu.setTabOrder(self.tbDataLat, self.eNOut)
        MainMenu.setTabOrder(self.eNOut, self.eAlpha)
        MainMenu.setTabOrder(self.eAlpha, self.eMinE)
        MainMenu.setTabOrder(self.eMinE, self.eIte)
        MainMenu.setTabOrder(self.eIte, self.eWaktu)
        MainMenu.setTabOrder(self.eWaktu, self.eMSE)
        MainMenu.setTabOrder(self.eMSE, self.pbBaca)
        MainMenu.setTabOrder(self.pbBaca, self.pbBobot)
        MainMenu.setTabOrder(self.pbBobot, self.pbPelatihan)
        MainMenu.setTabOrder(self.pbPelatihan, self.pbPengujian)
        MainMenu.setTabOrder(self.pbPengujian, self.eTotalDUji)
        MainMenu.setTabOrder(self.eTotalDUji, self.eWaktu_2)
        MainMenu.setTabOrder(self.eWaktu_2, self.eMSE_2)
        MainMenu.setTabOrder(self.eMSE_2, self.eAkurasi)
        MainMenu.setTabOrder(self.eAkurasi, self.eTotalDLatih)
        MainMenu.setTabOrder(self.eTotalDLatih, self.eNInp)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Menu Pelatihan"))
        self.judul.setText(_translate("MainMenu", "Menu Pelatihan ANN Backpropagation"))
        self.f_pengujian.setTitle(_translate("MainMenu", "Proses Pengujian"))
        self.Tombol_2.setTitle(_translate("MainMenu", "Tombol Kontrol"))
        self.pbBaca_2.setToolTip(_translate("MainMenu", "Membaca data pengujian"))
        self.pbBaca_2.setText(_translate("MainMenu", "Baca Data"))
        self.pbPengujian.setText(_translate("MainMenu", "Proses Pengujian"))
        self.TotalData_2.setTitle(_translate("MainMenu", "Total Data"))
        self.eTotalDUji.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eTotalDUji.setText(_translate("MainMenu", "0"))
        self.Iterasi_2.setTitle(_translate("MainMenu", "Iterasi & MSE"))
        self.lWaktu_2.setText(_translate("MainMenu", "Waktu Pelatihan (Detik)"))
        self.eWaktu_2.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eWaktu_2.setText(_translate("MainMenu", "0"))
        self.lMSE_2.setToolTip(_translate("MainMenu", "Mean Square Error"))
        self.lMSE_2.setText(_translate("MainMenu", "MSE"))
        self.eMSE_2.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eMSE_2.setText(_translate("MainMenu", "0"))
        self.lAkurasi.setText(_translate("MainMenu", "Rata-rata Akurasi (%)"))
        self.eAkurasi.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eAkurasi.setText(_translate("MainMenu", "0"))
        self.groupBox.setTitle(_translate("MainMenu", "Hasil Grafik Akurasi"))
        self.pbDetailG_2.setToolTip(_translate("MainMenu", "Melihat hasil detail grafik akurasi pengujian"))
        self.pbDetailG_2.setText(_translate("MainMenu", "Lihat Grafik Akurasi"))
        self.pbKelola.setText(_translate("MainMenu", "Kelola Data Pelatihan"))
        self.pbCetak.setText(_translate("MainMenu", "Cetak Hasil Pelatihan"))
        self.DataUji.setTitle(_translate("MainMenu", "Normalisasi Data Uji"))
        self.tbDataUji.setSortingEnabled(True)
        item = self.tbDataUji.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "NIM"))
        item = self.tbDataUji.horizontalHeaderItem(1)
        item.setText(_translate("MainMenu", "IPS 1"))
        item = self.tbDataUji.horizontalHeaderItem(2)
        item.setText(_translate("MainMenu", "IPS 2"))
        item = self.tbDataUji.horizontalHeaderItem(3)
        item.setText(_translate("MainMenu", "IPS 3"))
        item = self.tbDataUji.horizontalHeaderItem(4)
        item.setText(_translate("MainMenu", "IPS 4"))
        item = self.tbDataUji.horizontalHeaderItem(5)
        item.setText(_translate("MainMenu", "Fisika 1"))
        item = self.tbDataUji.horizontalHeaderItem(6)
        item.setText(_translate("MainMenu", "Matematika 1"))
        item = self.tbDataUji.horizontalHeaderItem(7)
        item.setText(_translate("MainMenu", "Fisika 2"))
        item = self.tbDataUji.horizontalHeaderItem(8)
        item.setText(_translate("MainMenu", "Matematika 2"))
        item = self.tbDataUji.horizontalHeaderItem(9)
        item.setText(_translate("MainMenu", "Algoritma Pemograman"))
        item = self.tbDataUji.horizontalHeaderItem(10)
        item.setText(_translate("MainMenu", "Elektronika 1"))
        item = self.tbDataUji.horizontalHeaderItem(11)
        item.setText(_translate("MainMenu", "Teori Sistem & Sinyal"))
        item = self.tbDataUji.horizontalHeaderItem(12)
        item.setText(_translate("MainMenu", "Organisasi & Arsitektur Komputer 1"))
        item = self.tbDataUji.horizontalHeaderItem(13)
        item.setText(_translate("MainMenu", "Sistem Digital"))
        item = self.tbDataUji.horizontalHeaderItem(14)
        item.setText(_translate("MainMenu", "Elektronika 2"))
        item = self.tbDataUji.horizontalHeaderItem(15)
        item.setText(_translate("MainMenu", "Struktur Data"))
        item = self.tbDataUji.horizontalHeaderItem(16)
        item.setText(_translate("MainMenu", "Matematika Diskrit"))
        item = self.tbDataUji.horizontalHeaderItem(17)
        item.setText(_translate("MainMenu", "Komunikasi Data"))
        item = self.tbDataUji.horizontalHeaderItem(18)
        item.setText(_translate("MainMenu", "Aljabar Liniear"))
        item = self.tbDataUji.horizontalHeaderItem(19)
        item.setText(_translate("MainMenu", "IPK"))
        self.HasilUji.setTitle(_translate("MainMenu", "Hasil Pengujian"))
        self.tbHasilUji.setSortingEnabled(True)
        item = self.tbHasilUji.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "NIM"))
        item = self.tbHasilUji.horizontalHeaderItem(1)
        item.setText(_translate("MainMenu", "Hasil Prediksi JST"))
        item = self.tbHasilUji.horizontalHeaderItem(2)
        item.setText(_translate("MainMenu", "Output Sebenarnya"))
        item = self.tbHasilUji.horizontalHeaderItem(3)
        item.setText(_translate("MainMenu", "Error"))
        item = self.tbHasilUji.horizontalHeaderItem(4)
        item.setText(_translate("MainMenu", "Akurasi"))
        self.pbLogout.setToolTip(_translate("MainMenu", "Kembali ke menu Utama"))
        self.pbLogout.setText(_translate("MainMenu", "Logout"))
        self.pbTambah.setToolTip(_translate("MainMenu", "Genarate Uniqe key untuk menambah Admin"))
        self.pbTambah.setText(_translate("MainMenu", "Tambah Admin"))
        self.f_pelatihan.setTitle(_translate("MainMenu", "Proses Pelatihan"))
        self.Tombol.setTitle(_translate("MainMenu", "Tombol Kontrol"))
        self.pbBaca.setToolTip(_translate("MainMenu", "Membaca data pelatihan"))
        self.pbBaca.setText(_translate("MainMenu", "Baca Data"))
        self.pbBobot.setToolTip(_translate("MainMenu", "Membaca bobot dan bias awal"))
        self.pbBobot.setText(_translate("MainMenu", "Bobot Awal"))
        self.pbPelatihan.setText(_translate("MainMenu", "Proses Pelatihan"))
        self.TotalData.setTitle(_translate("MainMenu", "Total Data"))
        self.eTotalDLatih.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eTotalDLatih.setText(_translate("MainMenu", "0"))
        self.Parameter.setTitle(_translate("MainMenu", "Parameter"))
        self.lNInp.setToolTip(_translate("MainMenu", "Banyak Neuron Input"))
        self.lNInp.setText(_translate("MainMenu", "N.Input"))
        self.lNHid.setToolTip(_translate("MainMenu", "Banyak Neuron Hidden"))
        self.lNHid.setText(_translate("MainMenu", "N.Hidden"))
        self.lNOut.setToolTip(_translate("MainMenu", "Banyak Neuron Output"))
        self.lNOut.setText(_translate("MainMenu", "N.Output"))
        self.lAlpha.setToolTip(_translate("MainMenu", "Alpha (Learning Rate)"))
        self.lAlpha.setText(_translate("MainMenu", "Alpha"))
        self.lMinE.setToolTip(_translate("MainMenu", "Minimum Error"))
        self.lMinE.setText(_translate("MainMenu", "Min.Error"))
        self.lIte.setToolTip(_translate("MainMenu", "Iterasi (Siklus Pelatihan)"))
        self.lIte.setText(_translate("MainMenu", "Iterasi"))
        self.eNInp.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eNInp.setText(_translate("MainMenu", "18"))
        self.eNHid.setToolTip(_translate("MainMenu", "Usahakan tidak lebih dari 50"))
        self.eNHid.setText(_translate("MainMenu", "24"))
        self.eNOut.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eNOut.setText(_translate("MainMenu", "1"))
        self.eAlpha.setToolTip(_translate("MainMenu", "Untuk penulisan desimal gunakan tanda titik(.)"))
        self.eAlpha.setText(_translate("MainMenu", "0.15"))
        self.eMinE.setToolTip(_translate("MainMenu", "Untuk penulisan desimal gunakan tanda titik(.)"))
        self.eMinE.setText(_translate("MainMenu", "0.001"))
        self.eIte.setText(_translate("MainMenu", "200"))
        self.Iterasi.setTitle(_translate("MainMenu", "Iterasi & MSE"))
        self.lWaktu.setText(_translate("MainMenu", "Waktu Pelatihan (Detik)"))
        self.eWaktu.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eWaktu.setText(_translate("MainMenu", "0"))
        self.lMSE.setToolTip(_translate("MainMenu", "Mean Square Error"))
        self.lMSE.setText(_translate("MainMenu", "MSE"))
        self.eMSE.setToolTip(_translate("MainMenu", "Maaf tidak bisa diubah"))
        self.eMSE.setText(_translate("MainMenu", "0"))
        self.TombolGrafik.setTitle(_translate("MainMenu", "Hasil Grafik MSE"))
        self.pbDetailG.setToolTip(_translate("MainMenu", "Melihat hasil detail grafik MSE pelatihan"))
        self.pbDetailG.setText(_translate("MainMenu", "Lihat Grafik MSE"))
        self.BobotHasil.setTitle(_translate("MainMenu", "Bias dan Bobot"))
        self.lBobotV.setText(_translate("MainMenu", "Bobot V"))
        self.lBobotW.setText(_translate("MainMenu", "Bobot W"))
        self.DataLatih.setTitle(_translate("MainMenu", "Normalisasi Data Latih"))
        self.tbDataLat.setSortingEnabled(True)
        item = self.tbDataLat.horizontalHeaderItem(0)
        item.setText(_translate("MainMenu", "NIM"))
        item = self.tbDataLat.horizontalHeaderItem(1)
        item.setText(_translate("MainMenu", "IPS 1"))
        item = self.tbDataLat.horizontalHeaderItem(2)
        item.setText(_translate("MainMenu", "IPS 2"))
        item = self.tbDataLat.horizontalHeaderItem(3)
        item.setText(_translate("MainMenu", "IPS 3"))
        item = self.tbDataLat.horizontalHeaderItem(4)
        item.setText(_translate("MainMenu", "IPS 4"))
        item = self.tbDataLat.horizontalHeaderItem(5)
        item.setText(_translate("MainMenu", "Fiska 1"))
        item = self.tbDataLat.horizontalHeaderItem(6)
        item.setText(_translate("MainMenu", "Matematika 1"))
        item = self.tbDataLat.horizontalHeaderItem(7)
        item.setText(_translate("MainMenu", "Fisika 2"))
        item = self.tbDataLat.horizontalHeaderItem(8)
        item.setText(_translate("MainMenu", "Matematika 2"))
        item = self.tbDataLat.horizontalHeaderItem(9)
        item.setText(_translate("MainMenu", "Algoritma Pemograman"))
        item = self.tbDataLat.horizontalHeaderItem(10)
        item.setText(_translate("MainMenu", "Elektronika 1"))
        item = self.tbDataLat.horizontalHeaderItem(11)
        item.setText(_translate("MainMenu", "Teori Sistem & Sinyal"))
        item = self.tbDataLat.horizontalHeaderItem(12)
        item.setText(_translate("MainMenu", "Organisasi & Arsitektur Komputer 1"))
        item = self.tbDataLat.horizontalHeaderItem(13)
        item.setText(_translate("MainMenu", "Sistem Digital"))
        item = self.tbDataLat.horizontalHeaderItem(14)
        item.setText(_translate("MainMenu", "Elektronika 2"))
        item = self.tbDataLat.horizontalHeaderItem(15)
        item.setText(_translate("MainMenu", "Struktur Data"))
        item = self.tbDataLat.horizontalHeaderItem(16)
        item.setText(_translate("MainMenu", "Matematika Diskrit"))
        item = self.tbDataLat.horizontalHeaderItem(17)
        item.setText(_translate("MainMenu", "Komunikasi Data"))
        item = self.tbDataLat.horizontalHeaderItem(18)
        item.setText(_translate("MainMenu", "Aljabar Linear"))
        item = self.tbDataLat.horizontalHeaderItem(19)
        item.setText(_translate("MainMenu", "IPK"))
        self.lHelo.setText(_translate("MainMenu", "Hello,"))
        self.lAdmin.setText(_translate("MainMenu", "Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())
