# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_kelola.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Main/logo_unikom_kuning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lHelo = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lHelo.sizePolicy().hasHeightForWidth())
        self.lHelo.setSizePolicy(sizePolicy)
        self.lHelo.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lHelo.setFont(font)
        self.lHelo.setIndent(5)
        self.lHelo.setObjectName("lHelo")
        self.horizontalLayout_2.addWidget(self.lHelo)
        self.lAdmin = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lAdmin.setFont(font)
        self.lAdmin.setIndent(-1)
        self.lAdmin.setObjectName("lAdmin")
        self.horizontalLayout_2.addWidget(self.lAdmin)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lHelo_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lHelo_2.sizePolicy().hasHeightForWidth())
        self.lHelo_2.setSizePolicy(sizePolicy)
        self.lHelo_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lHelo_2.setFont(font)
        self.lHelo_2.setIndent(5)
        self.lHelo_2.setObjectName("lHelo_2")
        self.horizontalLayout_2.addWidget(self.lHelo_2)
        self.pbLatih = QtWidgets.QPushButton(self.frame)
        self.pbLatih.setMinimumSize(QtCore.QSize(100, 30))
        self.pbLatih.setCheckable(True)
        self.pbLatih.setChecked(False)
        self.pbLatih.setAutoDefault(False)
        self.pbLatih.setDefault(False)
        self.pbLatih.setFlat(False)
        self.pbLatih.setObjectName("pbLatih")
        self.horizontalLayout_2.addWidget(self.pbLatih)
        self.pbUji = QtWidgets.QPushButton(self.frame)
        self.pbUji.setMinimumSize(QtCore.QSize(100, 30))
        self.pbUji.setCheckable(True)
        self.pbUji.setObjectName("pbUji")
        self.horizontalLayout_2.addWidget(self.pbUji)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pbKembali = QtWidgets.QPushButton(self.frame)
        self.pbKembali.setMinimumSize(QtCore.QSize(100, 30))
        self.pbKembali.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbKembali.setObjectName("pbKembali")
        self.horizontalLayout_2.addWidget(self.pbKembali)
        self.verticalLayout_2.addWidget(self.frame)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gInputData = QtWidgets.QGroupBox(self.groupBox)
        self.gInputData.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gInputData.setFlat(True)
        self.gInputData.setCheckable(False)
        self.gInputData.setObjectName("gInputData")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gInputData)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_30 = QtWidgets.QLabel(self.gInputData)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 3, 15, 1, 1)
        self.leX9 = QtWidgets.QLineEdit(self.gInputData)
        self.leX9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX9.setObjectName("leX9")
        self.gridLayout_3.addWidget(self.leX9, 1, 15, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gInputData)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 15, 1, 1)
        self.leX8 = QtWidgets.QLineEdit(self.gInputData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leX8.sizePolicy().hasHeightForWidth())
        self.leX8.setSizePolicy(sizePolicy)
        self.leX8.setMinimumSize(QtCore.QSize(70, 0))
        self.leX8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX8.setBaseSize(QtCore.QSize(0, 0))
        self.leX8.setObjectName("leX8")
        self.gridLayout_3.addWidget(self.leX8, 1, 14, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gInputData)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 6, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gInputData)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 14, 1, 1)
        self.leX7 = QtWidgets.QLineEdit(self.gInputData)
        self.leX7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX7.setObjectName("leX7")
        self.gridLayout_3.addWidget(self.leX7, 1, 12, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gInputData)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 12, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gInputData)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gInputData)
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gInputData)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gInputData)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 10, 1, 1)
        self.label = QtWidgets.QLabel(self.gInputData)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.leNIM = QtWidgets.QLineEdit(self.gInputData)
        self.leNIM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leNIM.setObjectName("leNIM")
        self.gridLayout_3.addWidget(self.leNIM, 1, 0, 1, 1)
        self.leX4 = QtWidgets.QLineEdit(self.gInputData)
        self.leX4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX4.setObjectName("leX4")
        self.gridLayout_3.addWidget(self.leX4, 1, 7, 1, 1)
        self.leX2 = QtWidgets.QLineEdit(self.gInputData)
        self.leX2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX2.setObjectName("leX2")
        self.gridLayout_3.addWidget(self.leX2, 1, 4, 1, 1)
        self.leX1 = QtWidgets.QLineEdit(self.gInputData)
        self.leX1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX1.setObjectName("leX1")
        self.gridLayout_3.addWidget(self.leX1, 1, 2, 1, 1)
        self.leX3 = QtWidgets.QLineEdit(self.gInputData)
        self.leX3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX3.setObjectName("leX3")
        self.gridLayout_3.addWidget(self.leX3, 1, 6, 1, 1)
        self.leX6 = QtWidgets.QLineEdit(self.gInputData)
        self.leX6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX6.setObjectName("leX6")
        self.gridLayout_3.addWidget(self.leX6, 1, 10, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gInputData)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 4, 1, 1)
        self.leX5 = QtWidgets.QLineEdit(self.gInputData)
        self.leX5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX5.setObjectName("leX5")
        self.gridLayout_3.addWidget(self.leX5, 1, 9, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gInputData)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 7, 1, 1)
        self.leX17 = QtWidgets.QLineEdit(self.gInputData)
        self.leX17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX17.setObjectName("leX17")
        self.gridLayout_3.addWidget(self.leX17, 4, 12, 1, 1)
        self.leX15 = QtWidgets.QLineEdit(self.gInputData)
        self.leX15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX15.setObjectName("leX15")
        self.gridLayout_3.addWidget(self.leX15, 4, 9, 1, 1)
        self.leX16 = QtWidgets.QLineEdit(self.gInputData)
        self.leX16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX16.setObjectName("leX16")
        self.gridLayout_3.addWidget(self.leX16, 4, 10, 1, 1)
        self.leX11 = QtWidgets.QLineEdit(self.gInputData)
        self.leX11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX11.setObjectName("leX11")
        self.gridLayout_3.addWidget(self.leX11, 4, 2, 1, 1)
        self.leX10 = QtWidgets.QLineEdit(self.gInputData)
        self.leX10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX10.setObjectName("leX10")
        self.gridLayout_3.addWidget(self.leX10, 4, 0, 1, 1)
        self.leX12 = QtWidgets.QLineEdit(self.gInputData)
        self.leX12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX12.setObjectName("leX12")
        self.gridLayout_3.addWidget(self.leX12, 4, 4, 1, 1)
        self.leX14 = QtWidgets.QLineEdit(self.gInputData)
        self.leX14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX14.setObjectName("leX14")
        self.gridLayout_3.addWidget(self.leX14, 4, 7, 1, 1)
        self.leIPK = QtWidgets.QLineEdit(self.gInputData)
        self.leIPK.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leIPK.setObjectName("leIPK")
        self.gridLayout_3.addWidget(self.leIPK, 4, 15, 1, 1)
        self.leX13 = QtWidgets.QLineEdit(self.gInputData)
        self.leX13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX13.setObjectName("leX13")
        self.gridLayout_3.addWidget(self.leX13, 4, 6, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gInputData)
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 3, 14, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gInputData)
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 3, 12, 1, 1)
        self.leX18 = QtWidgets.QLineEdit(self.gInputData)
        self.leX18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leX18.setObjectName("leX18")
        self.gridLayout_3.addWidget(self.leX18, 4, 14, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gInputData)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gInputData)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gInputData)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_11.setFont(font)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 4, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gInputData)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 3, 9, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gInputData)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 3, 7, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gInputData)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 3, 10, 1, 1)
        self.verticalLayout.addWidget(self.gInputData)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pbSearch = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSearch.sizePolicy().hasHeightForWidth())
        self.pbSearch.setSizePolicy(sizePolicy)
        self.pbSearch.setMinimumSize(QtCore.QSize(100, 30))
        self.pbSearch.setAutoExclusive(False)
        self.pbSearch.setAutoDefault(False)
        self.pbSearch.setDefault(False)
        self.pbSearch.setFlat(False)
        self.pbSearch.setObjectName("pbSearch")
        self.horizontalLayout_3.addWidget(self.pbSearch)
        self.pbTambah = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbTambah.sizePolicy().hasHeightForWidth())
        self.pbTambah.setSizePolicy(sizePolicy)
        self.pbTambah.setMinimumSize(QtCore.QSize(100, 30))
        self.pbTambah.setAutoExclusive(False)
        self.pbTambah.setAutoDefault(False)
        self.pbTambah.setDefault(False)
        self.pbTambah.setFlat(False)
        self.pbTambah.setObjectName("pbTambah")
        self.horizontalLayout_3.addWidget(self.pbTambah)
        self.pbUpdate = QtWidgets.QPushButton(self.groupBox_2)
        self.pbUpdate.setMinimumSize(QtCore.QSize(100, 30))
        self.pbUpdate.setObjectName("pbUpdate")
        self.horizontalLayout_3.addWidget(self.pbUpdate)
        self.pbTmbFile = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbTmbFile.sizePolicy().hasHeightForWidth())
        self.pbTmbFile.setSizePolicy(sizePolicy)
        self.pbTmbFile.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pbTmbFile.setFont(font)
        self.pbTmbFile.setMouseTracking(False)
        self.pbTmbFile.setCheckable(False)
        self.pbTmbFile.setChecked(False)
        self.pbTmbFile.setAutoExclusive(False)
        self.pbTmbFile.setAutoDefault(False)
        self.pbTmbFile.setDefault(False)
        self.pbTmbFile.setFlat(False)
        self.pbTmbFile.setObjectName("pbTmbFile")
        self.horizontalLayout_3.addWidget(self.pbTmbFile)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pbClear = QtWidgets.QPushButton(self.groupBox_2)
        self.pbClear.setMinimumSize(QtCore.QSize(100, 30))
        self.pbClear.setObjectName("pbClear")
        self.horizontalLayout_3.addWidget(self.pbClear)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pbHapusOne = QtWidgets.QPushButton(self.groupBox_2)
        self.pbHapusOne.setMinimumSize(QtCore.QSize(100, 30))
        self.pbHapusOne.setObjectName("pbHapusOne")
        self.horizontalLayout_3.addWidget(self.pbHapusOne)
        self.pbHapusAll = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbHapusAll.sizePolicy().hasHeightForWidth())
        self.pbHapusAll.setSizePolicy(sizePolicy)
        self.pbHapusAll.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pbHapusAll.setFont(font)
        self.pbHapusAll.setAutoExclusive(False)
        self.pbHapusAll.setAutoDefault(False)
        self.pbHapusAll.setDefault(False)
        self.pbHapusAll.setFlat(False)
        self.pbHapusAll.setObjectName("pbHapusAll")
        self.horizontalLayout_3.addWidget(self.pbHapusAll)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.glistdata = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.glistdata.setFont(font)
        self.glistdata.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.glistdata.setFlat(True)
        self.glistdata.setCheckable(False)
        self.glistdata.setObjectName("glistdata")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.glistdata)
        self.horizontalLayout.setContentsMargins(-1, 9, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbDataPre = QtWidgets.QTableWidget(self.glistdata)
        self.tbDataPre.setMinimumSize(QtCore.QSize(0, 0))
        self.tbDataPre.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tbDataPre.setAutoFillBackground(True)
        self.tbDataPre.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbDataPre.setDragDropOverwriteMode(False)
        self.tbDataPre.setAlternatingRowColors(True)
        self.tbDataPre.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbDataPre.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbDataPre.setObjectName("tbDataPre")
        self.tbDataPre.setColumnCount(20)
        self.tbDataPre.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tbDataPre.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tbDataPre.setHorizontalHeaderItem(19, item)
        self.tbDataPre.horizontalHeader().setDefaultSectionSize(67)
        self.horizontalLayout.addWidget(self.tbDataPre)
        self.verticalLayout.addWidget(self.glistdata)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        regex = QtCore.QRegExp("[0-9_]+")
        dv = QtGui.QDoubleValidator(0.99,99.99,2)
        validator = QtGui.QRegExpValidator(regex)
        self.leNIM.setValidator(validator)
        self.leNIM.setMaxLength(8)
        self.leX1.setValidator(dv)
        self.leX1.setMaxLength(6)
        self.leX2.setValidator(dv)
        self.leX2.setMaxLength(6)
        self.leX3.setValidator(dv)
        self.leX3.setMaxLength(6)
        self.leX4.setValidator(dv)
        self.leX4.setMaxLength(6)
        self.leX5.setValidator(validator)
        self.leX5.setMaxLength(1)
        self.leX6.setValidator(validator)
        self.leX6.setMaxLength(1)
        self.leX7.setValidator(validator)
        self.leX7.setMaxLength(1)
        self.leX8.setValidator(validator)
        self.leX8.setMaxLength(1)
        self.leX9.setValidator(validator)
        self.leX9.setMaxLength(1)
        self.leX10.setValidator(validator)
        self.leX10.setMaxLength(1)
        self.leX11.setValidator(validator)
        self.leX11.setMaxLength(1)
        self.leX12.setValidator(validator)
        self.leX12.setMaxLength(1)
        self.leX13.setValidator(validator)
        self.leX13.setMaxLength(1)
        self.leX14.setValidator(validator)
        self.leX14.setMaxLength(1)
        self.leX15.setValidator(validator)
        self.leX15.setMaxLength(1)
        self.leX16.setValidator(validator)
        self.leX16.setMaxLength(1)
        self.leX17.setValidator(validator)
        self.leX17.setMaxLength(1)
        self.leX18.setValidator(validator)
        self.leX18.setMaxLength(1)
        self.leIPK.setValidator(dv)
        self.leIPK.setMaxLength(6)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lHelo.setText(_translate("MainWindow", "Hello,"))
        self.lAdmin.setText(_translate("MainWindow", "Admin"))
        self.lHelo_2.setText(_translate("MainWindow", "Pilih Data :"))
        self.pbLatih.setText(_translate("MainWindow", "Data Latih"))
        self.pbUji.setText(_translate("MainWindow", "Data Uji"))
        self.pbKembali.setToolTip(_translate("MainWindow", "Kembali ke menu pelatihan"))
        self.pbKembali.setText(_translate("MainWindow", "Kembali"))
        self.groupBox.setTitle(_translate("MainWindow", "Input Data Akademik Mahasiswa"))
        self.gInputData.setTitle(_translate("MainWindow", "Input Data"))
        self.label_30.setText(_translate("MainWindow", "IPK"))
        self.leX9.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.label_8.setText(_translate("MainWindow", "Algoritma Pemograman"))
        self.leX8.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.label_23.setText(_translate("MainWindow", "Sistem Digital"))
        self.label_26.setText(_translate("MainWindow", "Matematika 2"))
        self.leX7.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.label_7.setText(_translate("MainWindow", "Fisika 2"))
        self.label_2.setText(_translate("MainWindow", "IPS 1"))
        self.label_27.setText(_translate("MainWindow", "IPS 3"))
        self.label_5.setText(_translate("MainWindow", "Fisika 1"))
        self.label_6.setText(_translate("MainWindow", "Matematika 1"))
        self.label.setText(_translate("MainWindow", "NIM"))
        self.leNIM.setPlaceholderText(_translate("MainWindow", "102XXXXX"))
        self.leX4.setPlaceholderText(_translate("MainWindow", "0.0 - 4.0"))
        self.leX2.setPlaceholderText(_translate("MainWindow", "0.0 - 4.0"))
        self.leX1.setPlaceholderText(_translate("MainWindow", "0.0 - 4.0"))
        self.leX3.setPlaceholderText(_translate("MainWindow", "0.0 - 4.0"))
        self.leX6.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.label_3.setText(_translate("MainWindow", "IPS 2"))
        self.leX5.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.label_4.setText(_translate("MainWindow", "IPS 4"))
        self.leX17.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.leX15.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.leX16.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.leX11.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.leX10.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.leX12.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.leX14.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.leIPK.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.leX13.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.label_29.setText(_translate("MainWindow", "Aljabar Linier"))
        self.label_28.setText(_translate("MainWindow", "Komunikasi Data"))
        self.leX18.setPlaceholderText(_translate("MainWindow", "0 - 4"))
        self.label_9.setText(_translate("MainWindow", "Elektronika 1"))
        self.label_10.setText(_translate("MainWindow", "Teori Sistem & Sinyal"))
        self.label_11.setText(_translate("MainWindow", "Organisasi & Arsitektur Komp."))
        self.label_25.setText(_translate("MainWindow", "Struktur Data"))
        self.label_24.setText(_translate("MainWindow", "Elektronika 2"))
        self.label_31.setText(_translate("MainWindow", "Matematika Diskrit"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Tombol Kontrol"))
        self.pbSearch.setText(_translate("MainWindow", "Cari"))
        self.pbTambah.setText(_translate("MainWindow", "Tambah"))
        self.pbUpdate.setText(_translate("MainWindow", "Ubah"))
        self.pbTmbFile.setToolTip(_translate("MainWindow", "Menambah data input dari file excel"))
        self.pbTmbFile.setText(_translate("MainWindow", "Tambah Data Dari File"))
        self.pbClear.setText(_translate("MainWindow", "Bersihkan Input"))
        self.pbHapusOne.setText(_translate("MainWindow", "Hapus"))
        self.pbHapusAll.setToolTip(_translate("MainWindow", "Menghapus semua data input pada tabel"))
        self.pbHapusAll.setText(_translate("MainWindow", "Hapus Semua\n"
"Input Data"))
        self.glistdata.setTitle(_translate("MainWindow", "Tabel Data"))
        self.tbDataPre.setSortingEnabled(False)
        item = self.tbDataPre.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NIM"))
        item = self.tbDataPre.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IPS 1"))
        item = self.tbDataPre.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "IPS 2"))
        item = self.tbDataPre.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "IPS 3"))
        item = self.tbDataPre.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "IPS 4"))
        item = self.tbDataPre.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fiska 1"))
        item = self.tbDataPre.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Matematika 1"))
        item = self.tbDataPre.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Fisika 2"))
        item = self.tbDataPre.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Matematika 2"))
        item = self.tbDataPre.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Algoritma Pemograman"))
        item = self.tbDataPre.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Elektronika 1"))
        item = self.tbDataPre.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Teori Sistem & Sinyal"))
        item = self.tbDataPre.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Organisasi & Arsitektur Komputer 1"))
        item = self.tbDataPre.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Sistem Digital"))
        item = self.tbDataPre.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Elektronika 2"))
        item = self.tbDataPre.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Struktur Data"))
        item = self.tbDataPre.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Matematika Diskrit"))
        item = self.tbDataPre.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Komunikasi Data"))
        item = self.tbDataPre.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Aljabar Linear"))
        item = self.tbDataPre.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "IPK"))
import gui.sourcesGambar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
